### ISSUE TITLE
Thank you for sharing your code. I was wondering if you could also share the RollingGuidanceFilter.m? It was used in the Filter.ipynb.

### ISSUE THREAD

**Issue by zhe-meng** [DotWang/MSHCN#1]

**Comment by DotWang** [comment]
@zhe-meng  Oh, the RollingGuidanceFilter is not used in this method. We use it to reproduce other paper. You can obtain it from http://www.cse.cuhk.edu.hk/leojia/projects/rollguidance/

**Comment by zhe-meng** [comment]
Thanks for your reply.

rgf_temp=engine.RollingGuidanceFilter(matlab.double(datalist),r,c,z,5,20,5)

According to your code, i guess that the default parameters of the RollingGuidanceFilter, i.e., sigma_s, sigma_r, and iteration, are 5, 20, and 5. 
And then using the RollingGuidanceFilter to filter each band of the HSI. Do I understand this correctly?

**Comment by zhe-meng** [comment]
@DotWang Thank you very much for your reply. It works.
![image](https://user-images.githubusercontent.com/26592180/233368160-5b8c0b14-7454-452c-9861-928fd4254bdf.png)
